version: "3.3"

services:
  gis:
    image: postgis/postgis
    container_name: postgis
    volumes:
      - ./data/db:/var/lib/postgis/data
    environment:
      - POSTGRES_DB=cyberphysical
      - POSTGRES_USER=cyberphysical
      - POSTGRES_PASSWORD=cyberpass
    ports:
      - "4321:4321"

  relstorage:
    image: postgres
    container_name: postgresdb
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=cyberphysical
      - POSTGRES_USER=cyberphysical
      - POSTGRES_PASSWORD=cyberpass
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    volumes:
      - ./data/redis:/var/lib/redis/data
    ports:
      - "6379:6379"

  cyber-physical-system:
    build: ./api/
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=relstorage
      - GIS_HOST=gis
      - DB_NAME=cyberphysical
      - DB_USER=cyberphysical
      - DB_PASS=cyberpass
      - REDIS_HOST=redis
    depends_on:
      - gis
      - relstorage
      - redis

  worker:
    build: ./api/
    container_name: roomworkers
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - DB_HOST=relstorage
      - GIS_HOST=gis
      - DB_NAME=cyberphysical
      - DB_USER=cyberphysical
      - DB_PASS=cyberpass
      - REDIS_HOST=redis
    depends_on:
      - cyber-physical-system

  web:
    build: ./vr/
    container_name: web
    volumes:
      - .:/webcode
    depends_on:
      - cyber-physical-system
    ports:
      - "3000:3000"
